# Generated by Django 4.0.3 on 2022-04-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInstagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
