# Generated by Django 4.0.3 on 2022-04-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInstagram', '0005_alter_comment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(blank=True, default='great', max_length=100),
        ),
    ]
